# Generated by Django 3.2.7 on 2023-08-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductDetails',
        ),
    ]
