# Generated by Django 3.2.7 on 2023-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_products_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_desc', models.TextField()),
                ('prod_price', models.PositiveIntegerField()),
                ('prod_img', models.FileField(upload_to='products/')),
            ],
        ),
    ]
